org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mc_version=1.12.2
forge_version=14.23.5.2847
mod_version=0.1.0
mod_group=com.demonicrous.limecore
mod_id=limecore
mod_name=Lime Core
mod_archives_name=LimeCore
mod_author=DemonicRous
mod_description=CoreMod foundation for Lime projects on Minecraft Forge 1.12.2.

